global:
  runner:
    containers:
      - image: ruby:2.6
      - image: redis
      - image: postgres:9.6-jessie
      environment:
        - RACK_ENV=test
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=discourse_test
        - DATABASE_URL="postgres://ubuntu@localhost:5432/discourse_test"


tasks:
  unit-tests:
    steps:
      - checkout
      - commands:
        - gem install bundler
        - bundle install || bundle check
        - RAILS_ENV=test bundle exec rake db:create db:migrate
        - bundle exec rake autospec

  # deploy-heroku:
  #   steps:
  #     - commands:
  #       - git branch
  #       - git push https://heroku:13bdb3ef-b2d8-4d73-a0cb-399732cba919@git.heroku.com/bnl.git origin/cicd:master
  #   when: branch == "cicd"
