global:
  runner:
    containers:
      - image: ruby:2.6
      - image: redis
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          - POSTGRES_DB=docker
          - POSTGRES_USER=root
  variables:
    - TEST_DATABASE_URL=postgres://root@localhost/docker
              

tasks:
  unit-tests:
    steps:
      - checkout
      - commands:
        - gem install bundler
        - bundle install || bundle check
        - RAILS_ENV=test bundle exec rake db:create db:migrate
        - bundle exec rake autospec

  # deploy-heroku:
  #   steps:
  #     - commands:
  #       - git branch
  #       - git push https://heroku:13bdb3ef-b2d8-4d73-a0cb-399732cba919@git.heroku.com/bnl.git origin/cicd:master
  #   when: branch == "cicd"
